import { Container } from "react-bootstrap";
import Head from "next/head";
import Header from "../header/index";

export default function Layout({ children }) {
  let Content = (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Container style={{ marginTop: "10rem" }}>
        <main>{children}</main>
      </Container>
    </>
  );

  return Content;
}
